# Generated by Django 5.0.2 on 2024-03-22 14:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrdentalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('7c3864ba-daa9-42b6-865b-b0fe27e12a91'), unique=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('1f749489-8c23-4953-967e-53610083791c'), unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('3efcbdf5-b2f3-4c81-b806-5983c19f399a'), unique=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('0423b7d0-f293-40e4-b22f-4c883bce80b6'), unique=True),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('ece5e320-d34d-4093-8d6e-26c1be71a0fa'), unique=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('fa0e3864-bd0f-44f4-a7d9-389f53569625'), unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('45e647e2-4713-496a-b01a-8c804adfd490'), unique=True),
        ),
    ]
