# Generated by Django 5.0.2 on 2024-04-08 11:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrdentalapp', '0003_alter_appointments_uu_alter_doctorprofile_uu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('913c26fd-fa5a-49c7-bd14-8d90b53c3178'), unique=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('a4805ea3-f7e4-4aef-9755-a547616a53a1'), unique=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('2d000133-b87d-4327-b098-72b04a34f26b'), unique=True),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('9158d9ac-3e4f-4838-a608-2c85b7dc5f63'), unique=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('139f1601-c456-458b-a62e-d8cc60308688'), unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('7f486b8e-b928-4bc6-bca1-94a3bd11d80f'), unique=True),
        ),
    ]
