# Generated by Django 5.0.2 on 2024-04-08 11:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrdentalapp', '0004_alter_appointments_uu_alter_doctorprofile_uu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatments',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('7a56ba68-8bbe-4dda-b40d-48e8bcf583f2'), unique=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('14960b45-e50a-41ce-94f8-81f25c8157d0'), unique=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('6b2c5697-9c56-4404-9c97-0fe2e6b045c8'), unique=True),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('b88b86d9-ab12-4452-9a34-dfcbc4a9266e'), unique=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('6bfceebc-3f94-4a0d-8436-6926a4c5214f'), unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('50dc8569-9426-4230-9a71-3b2b7c5435c0'), unique=True),
        ),
    ]
