# Generated by Django 5.0.2 on 2024-04-08 12:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrdentalapp', '0005_treatments_description_alter_appointments_uu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='adhaar_num',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='image',
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('e4312b35-7dff-402d-aa60-83433d814115'), unique=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('f020c37d-2d2f-479a-becb-eb29cc494d13'), unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('f138f2a3-0af7-4184-93e4-a432f337f497'), unique=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('ea3bded8-d3c9-4824-b6d1-dd8f4bfe1246'), unique=True),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('a0ee7092-1e7a-4655-9272-8938503011a4'), unique=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('28fb56a1-6704-4403-ad05-5dc76ad30994'), unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('41c26440-88e2-4713-9cd0-2a608cd8668c'), unique=True),
        ),
    ]
