# Generated by Django 5.0.2 on 2024-04-08 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrdentalapp', '0006_remove_patient_adhaar_num_remove_patient_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('862b9a4e-6810-4919-b692-88441bf67f3b'), unique=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('017de230-6848-46dd-bee6-c6613a6772af'), unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='uu',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('4fc935eb-0bb9-446c-bb97-585beab25c26'), unique=True),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('8500ebd2-26f8-46ec-a451-c3e9afdaab42'), unique=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('b504fe73-59a4-412f-99a5-2909df8a4c54'), unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('1f5646b3-158a-4754-aeb2-41873602640f'), unique=True),
        ),
    ]
