# Generated by Django 5.0.2 on 2024-04-15 06:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrdentalapp', '0007_alter_appointments_uu_alter_doctorprofile_uu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('380a9e3f-e264-4ccf-8b25-50a5694a1adb'), unique=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('4b7c9b4e-6b6b-47c0-adb6-06f76ba225b1'), unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('0421a589-9141-4e89-8ecf-287c89fbd061'), unique=True),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('3baf9bc7-f999-4b20-8efe-30c8c8f482bb'), unique=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='description',
            field=models.TextField(default='A dental procedure is that needs immediate attention from our expert dentist dental practitioner.'),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('c42995f2-63fb-4f00-af3a-2a268f686ed2'), unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('0d5f8cf8-5017-43b2-98f5-ec573f6878a3'), unique=True),
        ),
    ]
