# Generated by Django 5.0.2 on 2024-04-15 09:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrdentalapp', '0008_alter_appointments_uu_alter_doctorprofile_uu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='uu',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('a84ab689-77fe-421c-8127-a3d70eb8787a'), unique=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('1f9b8f96-4ad0-44e3-96d9-7036ad5fd6e7'), unique=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('db2ac6e9-77f0-4a47-93ba-8e144df8aec5'), unique=True),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('8b485191-e716-4c72-9a79-9f3900cdf13b'), unique=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('eb2c544c-afdb-48a8-9562-dde03ab98de5'), unique=True),
        ),
    ]
