# Generated by Django 5.0.2 on 2024-04-19 16:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrdentalapp', '0010_dentaleaseusers_delete_users_alter_appointments_uu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('797bc343-ba59-4d88-8fb2-ed28c13549a8'), unique=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('c1e6776b-e5cd-4031-abdd-e033ee2166a1'), unique=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('b932984f-4bc7-4513-ba5e-75d9d969efab'), unique=True),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('6b5b36ca-5147-4390-bdc0-edcf29e1ccc5'), unique=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('9c0c9f55-9f3c-42f7-b53d-12e53ec876e9'), unique=True),
        ),
    ]
