# Generated by Django 5.0.2 on 2024-04-19 17:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrdentalapp', '0012_alter_appointments_uu_alter_doctorprofile_uu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentaleaseusers',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dentaleaseusers',
            name='phone',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('029bbb84-36dc-4625-8dc5-ce5b677a7f50'), unique=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('35aa14cb-49bc-44b2-b0ca-30e4ebc2b68a'), unique=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('c113ab17-9d58-4c1a-83f9-92065de99ffe'), unique=True),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('58473e22-772b-43e8-9569-f71b6f2bfc91'), unique=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('1a2bb23a-70b7-49c9-8940-c9ca4f7ac38d'), unique=True),
        ),
    ]
