# Generated by Django 5.0.2 on 2024-05-05 10:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrdentalapp', '0013_dentaleaseusers_name_dentaleaseusers_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslots',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='timeslots',
            name='status',
        ),
        migrations.RemoveField(
            model_name='timeslots',
            name='to_time',
        ),
        migrations.AddField(
            model_name='timeslots',
            name='available_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timeslots',
            name='booked_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timeslots',
            name='max_slots',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('d842da2b-eed5-4b14-ab39-41c42deeb8f2'), unique=True),
        ),
        migrations.AlterField(
            model_name='dentaleaseusers',
            name='user_type',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'System User'), ('3', 'Patient')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('5c2e7f76-a824-4421-9af9-d62bb33b2809'), unique=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('9d03d006-d909-46e9-b559-331cf556de9f'), unique=True),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('4aef6e7c-3893-4bcd-b93f-52231d4a8d1b'), unique=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('2bf9d0c3-9d80-4ac0-abe2-cd49d72a7f6f'), unique=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='visibility_type',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'System User'), ('3', 'Patient')], default='1', max_length=1),
        ),
    ]
