# Generated by Django 5.0.2 on 2024-05-05 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrdentalapp', '0014_remove_timeslots_from_time_remove_timeslots_status_and_more'),
    ]

    operations = [
    ]