# Generated by Django 5.0.2 on 2024-05-05 11:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrdentalapp', '0015_auto_20240505_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('cc82c4c3-20f5-4af7-9840-665d3d02c9dd'), unique=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('11668217-468a-42f9-af04-bc186f0b5d74'), unique=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('d1e0091a-0833-46e2-8e17-dfd3d743b33c'), unique=True),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='uu',
            field=models.UUIDField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('c4bfa21c-d59d-4144-8d21-bda31b6c8c59'), unique=True),
        ),
    ]
