# Generated by Django 5.0.2 on 2024-05-05 11:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrdentalapp', '0016_alter_appointments_uu_alter_doctorprofile_uu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslots',
            name='uu',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('955a8775-c38d-4157-9353-5ed145d7cc74'), unique=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('92c1b676-6e0b-4dd9-b309-dde95f15e5a3'), unique=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('8f397a2e-6e90-4498-9701-117b25bfa0dd'), unique=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('594b7e87-905f-40c6-bfd6-63ec7ce670bb'), unique=True),
        ),
    ]
