# Generated by Django 5.0.2 on 2024-05-05 18:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrdentalapp', '0018_auto_20240505_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('Pending for approval', 'Pending for approval'), ('Confirmed', 'Confirmed'), ('Request for change', 'Request for change'), ('Cancelled', 'Cancelled')], default='Pending for approval', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='uu',
            field=models.UUIDField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('c1c35406-7d5e-484a-88e1-ad77e4e1e055'), unique=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('9f241110-a9e0-4162-a022-549b2fc52ab3'), unique=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('ffc2e89f-7aab-4d96-ae70-69fb01a2ce7a'), unique=True),
        ),
    ]
