# Generated by Django 5.0.2 on 2024-05-18 13:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrdentalapp', '0019_alter_appointments_status_alter_appointments_uu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciept',
            name='reciept_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('Pending for approval', 'Pending for approval'), ('Confirmed', 'Confirmed'), ('Request for change', 'Request for change'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending for approval', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('e672d520-966e-4484-abf8-8e1f18f9b4c9'), unique=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='uu',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('655aaf7e-82f8-4678-872e-2a1d437421e8'), unique=True),
        ),
    ]
