# Generated by Django 5.0.2 on 2024-05-18 13:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrdentalapp', '0020_reciept_reciept_file_alter_appointments_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('56efb4cb-017b-4246-a3d4-1f3decb6ab5d'), unique=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], max_length=20),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('1785c60c-4448-4f1f-87ff-2a2637c8871d'), unique=True),
        ),
    ]
