# Generated by Django 5.0.2 on 2024-05-18 19:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrdentalapp', '0021_alter_doctorprofile_uu_alter_reciept_payment_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('reciept_file', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('total_amount', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('9ad717b7-2eb2-41a2-b67a-96d9d4fed1db'), unique=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('bb37b0c0-542a-4dc1-8406-b918418d52ba'), unique=True),
        ),
    ]
