# Generated by Django 5.0.2 on 2024-05-18 19:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrdentalapp', '0022_monthlyreport_alter_doctorprofile_uu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyreport',
            old_name='reciept_file',
            new_name='report_file',
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('b07282fd-11f2-44ad-af1b-161cce8de03b'), unique=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='uu',
            field=models.UUIDField(default=uuid.UUID('0145294f-8e55-4937-b482-ddaafdd93653'), unique=True),
        ),
    ]
